FROM ubuntu:trusty

RUN apt-get update
RUN apt-get install -y software-properties-common

RUN add-apt-repository ppa:duggan/bats
RUN apt-get update -qq
RUN apt-get install -qq -y bats postgresql-client

WORKDIR /app
COPY test.sh /app
CMD ["bats", "test.sh"]
