- name: Install repmgr
  apt:
      name: "repmgr"
      update_cache: yes
      cache_valid_time: 86400
  become: yes

- name: Create repmgr log directory
  become: yes
  file:
    path: /var/log/repmgr
    state: directory
    owner: postgres
    group: postgres
    mode: 0775

- name: Stop postgres
  service: name=postgresql state=stopped
  become: yes

- name: Setup postgres configuration
  become: yes
  become_user: postgres
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.5/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0640

- name: Setup postgres access configuration
  become: yes
  become_user: postgres
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: Setup repmgr configuration
  become: yes
  template:
    src: repmgr.conf.j2
    dest: /etc/repmgr.conf
    owner: postgres
    group: postgres
    mode: 0640

- include: "./initialize.yml"
