- name: Install repmgr
  apt:
      name: "repmgr"
      update_cache: yes
      cache_valid_time: 86400
  become: yes

- name: Create repmgr log directory
  become: yes
  file:
    path: /var/log/repmgr
    state: directory
    owner: postgres
    group: postgres
    mode: 0775

- name: Stop postgres
  service: name=postgresql state=stopped
  become: yes

- name: Setup postgres configuration
  become: yes
  become_user: postgres
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.5/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0640

- name: Setup postgres access configuration
  become: yes
  become_user: postgres
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: Main exists?
  stat: path=/var/lib/postgresql/9.5/main
  register: main_stat
  changed_when: False

- name: Remove current data
  file:
    path: /var/lib/postgresql/9.5/main
    state: absent
  become: yes
  become_user: postgres
  when: main_stat.stat.exists

- name: Setup repmgr configuration
  become: yes
  template:
    src: repmgr.conf.j2
    dest: /etc/repmgr.conf
    owner: postgres
    group: postgres
    mode: 0640

- name: Clone the standby
  become: yes
  become_user: postgres
  command: repmgr -h {{ master_address }} -p 5432 -U repmgr -d repmgr -D /var/lib/postgresql/9.5/main --ignore-external-config-files standby clone
  register: clone_command
  failed_when: "clone_command.rc != 0"

- name: Start postgres
  service: name=postgresql state=started
  become: yes

- name: Register standby in repmgr
  become: yes
  become_user: postgres
  command: repmgr standby register
  register: repmgr_command
  failed_when: "repmgr_command.rc != 0"

- name: Run repmgr daemon
  become: yes
  become_user: postgres
  command: repmgrd -d -p /var/run/postgresql/repmgrd.pid
